import Head from "next/head";
import Image from "next/image";
import CardTest from "../components/CardTest";
import CardTest2 from "../components/CardTest2";
import CardTest3 from "../components/CardTest3";
import { ChevronRightIcon, DotsHorizontalIcon } from "@heroicons/react/solid";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center mt-20">
        <section className="flex-col h-full bg-gray-300/40 rounded-[2rem] mx-4">
          <div className="flex justify-between mx-7 mt-4">
            <h1 className="text-3xl font-semibold">In Progress</h1>
            <div className="flex items-center space-x-4">
              <DotsHorizontalIcon className="h-8 w-8 cursor-pointer text-gray-500" />
              <ChevronRightIcon className="h-10 w-10 cursor-pointer text-gray-500" />
            </div>
          </div>
          <CardTest />
          <CardTest2 />
          <CardTest3 />
        </section>
        <section className="flex-col h-full bg-gray-300/40 rounded-[2rem] mx-4">
          <div className="flex justify-between mx-7 mt-4">
            <h1 className="text-3xl font-semibold">Complete</h1>
            <div className="flex items-center space-x-4">
              <DotsHorizontalIcon className="h-8 w-8 cursor-pointer text-gray-500" />
              <ChevronRightIcon className="h-10 w-10 cursor-pointer text-gray-500" />
            </div>
          </div>
          <CardTest3 />
          <CardTest2 />
        </section>
      </div>
    </div>
  );
}
