import Head from 'next/head'
import Image from 'next/image'
import CardTest from '../components/CardTest'
import CardTest2 from '../components/CardTest2'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center mt-20">
        <section className="flex-col h-full bg-gray-300/30 rounded-[2rem]">
          <h1 className='text-3xl font-semibold ml-7 mt-4'>In Progress</h1>
          <CardTest />
          <CardTest2 />
        </section>
      </div>
    </div>
  );
}
